name: Build

on: [push, pull_request]

jobs:
  build:
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # EOL: April 2021
          - os: ubuntu-latest
            node_version: 10.x

          # EOL: April 2022
          - os: ubuntu-latest
            node_version: 12.x

          # EOL: April 2023
          - os: ubuntu-latest
            node_version: 14.x
          - os: macOS-latest
            node_version: 14.x
          - os: windows-latest
            node_version: 14.x

          # EOL: June 2021
          - os: ubuntu-latest
            node_version: 15.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup windows-build-tools
        if: matrix.os == 'windows-latest'
        run: npm i -g windows-build-tools

      - name: Install
        run: yarn --frozen-lockfile --non-interactive
        env:
          GYP_MSVS_OVERRIDE_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Test
        run: yarn test
